import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
// import Graph from '../utls/graph'
import { useEffect } from 'react'
class Graph {
	#vertices = new Set();
	#adjacentList = new Map();

	get vertices() {
		return Array.from(this.#vertices)
	}
	constructor() {

	}

	get adjacentList() {
		const list = {};

		this.#adjacentList.forEach((val, key) => {
			list[key] = Array.from(val)
		})

		return list
	}

	addVertex(vertex = null) {
		if (
			!this.#vertices.has(vertex) &&
			vertex !== null &&
			vertex !== undefined
		) {
			this.#vertices.add(vertex);
			this.#adjacentList.set(vertex, new Set());
		}
	}

	addEdge(vertex1 = null, vertex2 = null, directed = true) {
		if (
			vertex1 !== null && vertex1 !== undefined &&
			vertex2 !== null && vertex2 !== undefined &&
			vertex1 != vertex2
		) {
			this.addVertex(vertex1);
			this.addVertex(vertex2);
			this.#adjacentList.get(vertex1).add(vertex2);
			if (directed) {
				this.#adjacentList.get(vertex2).add(vertex1);
			}
		}
	}


}
export default function Home() {

	function aStarSearch(graph, start, goal) {
		paths = [start]
		let found = false
		while (paths.length != 0 && !found) {
			if (start[0] != goal) {
				paths.remove(start)
				paths.push()
			}
			else {

			}
		}
	}

	useEffect(() => {
		let x = new Graph()
		x.addVertex("Ar")
		x.addVertex("Si")
		x.addVertex("To")
		x.addVertex("Me")
		x.addEdge("Ar", "Si", true)
		x.addEdge("Ar", "To", true)
		x.addEdge("Si", "To", true)
		x.addEdge("Me", "To", true)
		console.log(x.vertices)
	}, [])
	function displayGraph(graph) {
		graph.vertices.map(vertex => {
			return <div></div>
		})
	}
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>


		</div>
	)
}
